#!/usr/bin/env python3
"""Regenerate src/main/resources/simplejs/emoji-sequences.txt.

The ECMA-262 "properties of strings" (`\\p{RGI_Emoji}` and friends, valid only under the regex `v`
flag) are sets of *strings*, not sets of code points, so `java.util.regex` has no data for them and
`RegexTranslator` expands each one into an alternation of literal sequences. The data therefore has
to ship with the engine as a resource.

It is pinned to the Unicode version the pinned test262 corpus targets (see UCD_VERSION below); the
per-code-point Unicode data used by the rest of the regex engine still comes from the build JDK, so
this is the one place where our Unicode tables are our own.

Source files: `emoji-sequences.txt` and `emoji-zwj-sequences.txt` from UTS #51. Unicode does not
publish an `emoji/17.0/` directory under www.unicode.org/Public (the emoji annex data files for that
release live only in the unicode-org/unicodetools repository), so the generator reads them from the
tagged raw files there.

Usage:
    python3 test_utils/gen_emoji_sequences.py            # download + rewrite the resource
    python3 test_utils/gen_emoji_sequences.py --check    # exit non-zero if the resource is stale
"""

from __future__ import annotations

import argparse
import pathlib
import sys
import urllib.request

UCD_VERSION = "17.0"
SOURCE_BASE = "https://raw.githubusercontent.com/unicode-org/unicodetools/main/unicodetools/data/emoji"
SOURCES = ("emoji-sequences.txt", "emoji-zwj-sequences.txt")

# The six properties of strings ECMA-262 recognises, minus RGI_Emoji, which is the union of the
# other five plus RGI_Emoji_ZWJ_Sequence (UTS #51 ED-27) and is derived at load time.
PROPERTIES = (
    "Basic_Emoji",
    "Emoji_Keycap_Sequence",
    "RGI_Emoji_Flag_Sequence",
    "RGI_Emoji_Modifier_Sequence",
    "RGI_Emoji_Tag_Sequence",
    "RGI_Emoji_ZWJ_Sequence",
)

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
RESOURCE = REPO_ROOT / "src" / "main" / "resources" / "simplejs" / "emoji-sequences.txt"


def fetch(name: str) -> str:
    url = f"{SOURCE_BASE}/{UCD_VERSION}/{name}"
    with urllib.request.urlopen(url, timeout=60) as response:
        return response.read().decode("utf-8")


def parse(text: str, entries: dict[str, list[str]]) -> None:
    for line in text.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        fields = [field.strip() for field in line.split(";")]
        if len(fields) < 2 or fields[1] not in PROPERTIES:
            continue
        for sequence in expand(fields[0]):
            bucket = entries.setdefault(fields[1], [])
            if sequence not in bucket:
                bucket.append(sequence)


def expand(codepoints: str) -> list[str]:
    points = codepoints.split()
    if len(points) == 1 and ".." in points[0]:
        low, high = points[0].split("..")
        return [f"{value:04X}" for value in range(int(low, 16), int(high, 16) + 1)]
    return [" ".join(point.upper() for point in points)]


def render(entries: dict[str, list[str]]) -> str:
    lines = [
        f"# Emoji sequence data for the ECMA-262 regex properties of strings. Unicode {UCD_VERSION}.",
        "# Generated by test_utils/gen_emoji_sequences.py -- do not edit by hand.",
        "# Format: <property><TAB><space-separated code points in hex>",
        "# RGI_Emoji is not listed: it is the union of every property below (UTS #51 ED-27).",
    ]
    for name in PROPERTIES:
        for sequence in entries.get(name, []):
            lines.append(f"{name}\t{sequence}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="verify the checked-in resource is current")
    args = parser.parse_args()

    entries: dict[str, list[str]] = {}
    for name in SOURCES:
        parse(fetch(name), entries)
    missing = [name for name in PROPERTIES if not entries.get(name)]
    if missing:
        print(f"no data parsed for: {', '.join(missing)}", file=sys.stderr)
        return 1

    content = render(entries)
    total = sum(len(values) for values in entries.values())
    if args.check:
        current = RESOURCE.read_text(encoding="utf-8") if RESOURCE.exists() else ""
        if current != content:
            print(f"{RESOURCE} is stale; re-run without --check", file=sys.stderr)
            return 1
        print(f"{RESOURCE} is up to date ({total} sequences, Unicode {UCD_VERSION})")
        return 0

    RESOURCE.parent.mkdir(parents=True, exist_ok=True)
    RESOURCE.write_text(content, encoding="utf-8")
    print(f"wrote {RESOURCE} ({total} sequences, Unicode {UCD_VERSION})")
    for name in PROPERTIES:
        print(f"  {name}: {len(entries[name])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
