package org.techhouse.cluster.msg;

public enum ClusterMessageType {
    JOIN_REQUEST, JOIN_RESPONSE, GOSSIP, GOSSIP_ACK, REPLICATE, REPLICATE_ACK, REPLICATE_ADMIN, REPLICATE_ADMIN_ACK, REPLICATE_USER, REPLICATE_USER_ACK, REPLICATE_TX, REPLICATE_TX_ACK, FORWARD_REQUEST, FORWARD_RESPONSE, FORWARD_TX_REQUEST, DIGEST, DIGEST_ACK, PULL, PULL_ACK, ERROR
}
