package org.techhouse.cluster.msg;

public enum ClusterMessageType {
    JOIN_REQUEST, JOIN_RESPONSE, GOSSIP, GOSSIP_ACK, REPLICATE, REPLICATE_ACK, REPLICATE_ADMIN, REPLICATE_ADMIN_ACK, REPLICATE_USER, REPLICATE_USER_ACK, REPLICATE_TX, REPLICATE_TX_ACK, FORWARD_REQUEST, FORWARD_RESPONSE, FORWARD_TX_REQUEST, PREPARE_TX, PREPARE_TX_ACK, COMMIT_TX, COMMIT_TX_ACK, ABORT_TX, ABORT_TX_ACK, TX_STATUS, TX_STATUS_ACK, LIST_TX, LIST_TX_ACK, LIST_SCRIPTS, LIST_SCRIPTS_ACK, CANCEL_SCRIPT, CANCEL_SCRIPT_ACK, LIST_TRIGGER_RUNS, LIST_TRIGGER_RUNS_ACK, RESOLVE_TRIGGER_RUN, RESOLVE_TRIGGER_RUN_ACK, ADMIN_SNAPSHOT, ADMIN_SNAPSHOT_ACK, DIGEST, DIGEST_ACK, PULL, PULL_ACK, ERROR
}
