package org.techhouse.ops;

public enum OperationType {
    BULK_SAVE, // INSERT, UPDATE
    SAVE, //INSERT, UPDATE
    FIND_BY_ID,
    AGGREGATE,
    DELETE,
    CREATE_DATABASE,
    DROP_DATABASE,
    LIST_DATABASES,
    CREATE_COLLECTION,
    DROP_COLLECTION,
    LIST_COLLECTIONS,
    CREATE_INDEX,
    DROP_INDEX,
    CLOSE_CONNECTION,
    AUTHENTICATE,
    CREATE_USER,
    DELETE_USER,
    CHANGE_PERMISSIONS,
    SET_DATABASE_OWNERS,
    LIST_USERS,
    SET_PASSWORD,
    GET_DATABASE_STATS
}
